service: serverless-test # Lambda関数を作成する際のプレフィクスに使われます。

provider:
  name: aws
  runtime: python3.6
  stage: dev # Lambda関数を作成する際のプレフィクスに使われます。
  profile: [profile-name] # ~/.aws/credentialsに作成したプロファイル名を指定します。
  region: ap-northeast-1
  memorySize: 128
  timeout: 10

custom:
 wsgi:
    app: api.app # api.pyに定義されている「app」という変数を指します。

plugins:
  - serverless-wsgi

# 不要なファイルがS3にアップロードされないよう、除外設定をしておきます。
package:
  exclude:
    - .git/**
    - node_modules/**

# corsの設定を含めておきます。
functions:
  api:
    handler: wsgi.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: serverlessTestGateway #この名前でAPI GatewayのAPIが作成されます。
